import React from 'react';
import Dropdown from 'react-dropdown';
import 'react-dropdown/style.css';

class Activity extends React.Component {
    render() {
        return (
            <Dropdown>
                <Dropdown.Toggle variant="success" id="dropdown-basic">
                    Dropdown Button
                </Dropdown.Toggle>

                <Dropdown.Menu>
                    <Dropdown.Item href="#/action-1">Action</Dropdown.Item>
                    <Dropdown.Item href="#/action-2">Another action</Dropdown.Item>
                    <Dropdown.Item href="#/action-3">Something else</Dropdown.Item>
                </Dropdown.Menu>
            </Dropdown>
        );
    }

    // Add drop down maintenance type list
    // CarId is fetched from API

    // id is generated by backend
    // date is in the record
    // needs to add store-record using AWS
}

export default Activity;