import React from 'react';
import Select from 'react-select';

const options = [
    { value: 'chocolate', label: 'Chocolate' },
    { value: 'strawberry', label: 'Strawberry' },
    { value: 'vanilla', label: 'Vanilla' },
];

class Activity extends React.Component {
    state = {
        selectedOption: null,
    };
    handleChange = selectedOption => {
        this.setState(
            { selectedOption },
            () => console.log(`Option selected:`, this.state.selectedOption)
        );
    };
    render() {
        const { selectedOption } = this.state;

        return (
            <Select
                maxMenuHeight={40}
                value={selectedOption}
                onChange={this.handleChange}
                options={options}
            />
        );
    }
}

// Add drop down maintenance type list
// CarId is fetched from API

// id is generated by backend
// date is in the record
// needs to add store-record using AWS

export default Activity;